'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace getCompStock
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://wmEAIprd01/USI_ASRS.getCompStock:getCompStock_WSD", ConfigurationName:="getCompStock.getCompStock_WSD_PortType")>  _
    Public Interface getCompStock_WSD_PortType
        
        'CODEGEN: 訊息部分命名空間 () 與預設值 (http://wmEAIprd01/USI_ASRS.getCompStock:getCompStock_WSD) 不符，正在產生訊息合約
        <System.ServiceModel.OperationContractAttribute(Action:="USI_ASRS_getCompStock_getCompStock_WSD_Binder_getCompStock", ReplyAction:="*")>  _
        Function getCompStock(ByVal request As getCompStock.getCompStockRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="XMLOutput")> getCompStock.getCompStockResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="USI_ASRS_getCompStock_getCompStock_WSD_Binder_getCompStock", ReplyAction:="*")>  _
        Function getCompStockAsync(ByVal request As getCompStock.getCompStockRequest) As System.Threading.Tasks.Task(Of getCompStock.getCompStockResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getCompStock", WrapperNamespace:="http://wmEAIprd01/USI_ASRS.getCompStock:getCompStock_WSD", IsWrapped:=true)>  _
    Partial Public Class getCompStockRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public S_DATE As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=1)>  _
        Public E_DATE As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal S_DATE As String, ByVal E_DATE As String)
            MyBase.New
            Me.S_DATE = S_DATE
            Me.E_DATE = E_DATE
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getCompStockResponse", WrapperNamespace:="http://wmEAIprd01/USI_ASRS.getCompStock:getCompStock_WSD", IsWrapped:=true)>  _
    Partial Public Class getCompStockResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="", Order:=0)>  _
        Public XMLOutput As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal XMLOutput As String)
            MyBase.New
            Me.XMLOutput = XMLOutput
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface getCompStock_WSD_PortTypeChannel
        Inherits getCompStock.getCompStock_WSD_PortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getCompStock_WSD_PortTypeClient
        Inherits System.ServiceModel.ClientBase(Of getCompStock.getCompStock_WSD_PortType)
        Implements getCompStock.getCompStock_WSD_PortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function getCompStock_getCompStock_WSD_PortType_getCompStock(ByVal request As getCompStock.getCompStockRequest) As getCompStock.getCompStockResponse Implements getCompStock.getCompStock_WSD_PortType.getCompStock
            Return MyBase.Channel.getCompStock(request)
        End Function
        
        Public Function getCompStock(ByVal S_DATE As String, ByVal E_DATE As String) As String
            Dim inValue As getCompStock.getCompStockRequest = New getCompStock.getCompStockRequest()
            inValue.S_DATE = S_DATE
            inValue.E_DATE = E_DATE
            Dim retVal As getCompStock.getCompStockResponse = CType(Me,getCompStock.getCompStock_WSD_PortType).getCompStock(inValue)
            Return retVal.XMLOutput
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function getCompStock_getCompStock_WSD_PortType_getCompStockAsync(ByVal request As getCompStock.getCompStockRequest) As System.Threading.Tasks.Task(Of getCompStock.getCompStockResponse) Implements getCompStock.getCompStock_WSD_PortType.getCompStockAsync
            Return MyBase.Channel.getCompStockAsync(request)
        End Function
        
        Public Function getCompStockAsync(ByVal S_DATE As String, ByVal E_DATE As String) As System.Threading.Tasks.Task(Of getCompStock.getCompStockResponse)
            Dim inValue As getCompStock.getCompStockRequest = New getCompStock.getCompStockRequest()
            inValue.S_DATE = S_DATE
            inValue.E_DATE = E_DATE
            Return CType(Me,getCompStock.getCompStock_WSD_PortType).getCompStockAsync(inValue)
        End Function
    End Class
End Namespace
